In [ ]:

import pandas as pd
import numpy as np
import re
file_path = "/content/The_Migration_Mindset_of_IT_Graduates_in_Sri_Lanka.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully")
print("Original shape:", df.shape)

df.head()

Dataset loaded successfully
Original shape: (96, 22)

,age,gender,marital_status,breadwinner,num_of_dep,uni_type,academic_spl,final_gpa,job_role,workplace,...,monthly_salary,percentage_of_living_expenses,current_job_role_sat_rate,family_living_abroad,relatives_abroad,friends_it_migrated,plan_to_migrate,primary_reasons_for_migrating,timeframe_planning_to_migrate,preferred_country
0,32,Male,Unmarried,No,0,Government (State),Computer Science,3.27,Entrepreneur,Beep technologies pvt ltd,...,"Below 200,000",40% - 60%,1,No,0,20,Undecided,Not applicable,Not applicable,Not applicable
1,28,Male,Unmarried,No,4,Government (State),Electronics and Information technology,3.40,QA Engineer / UI/UX Designer,MillenniumIT,...,"200,000 - 500,000",40% - 60%,3,No,3,10,Undecided,Not applicable,Not applicable,Not applicable
2,24,Male,Unmarried,No,2,Private,Computer Science,3.00,Software Engineer / Developer,LOLC Technologies,...,"Below 200,000",My expenditures exceed my income,2,No,0,5,Yes,Higher Salaries and Better Financial Prospects...,Needs review,Schengen Countries
3,30,Female,Married,No,4,Government (State),Computer Science and Industrial Management,3.24,Project Manager,Infor Sri Lanka,...,"200,000 - 500,000",40% - 60%,5,No,10,8,Undecided,Not applicable,Not applicable,Not applicable
4,29,Male,Married,No,0,Private,Software Engineering,3.69,Software Engineer / Developer,IFS,...,"200,000 - 500,000",61% - 80%,3,No,15,10,Undecided,Not applicable,Not applicable,Not applicable

In [ ]:
df = df.drop(columns=["Timestamp"], errors="ignore")

print("Timestamp removed")

df.head()

Timestamp removed

,age,gender,marital_status,breadwinner,num_of_dep,uni_type,academic_spl,final_gpa,job_role,workplace,...,monthly_salary,percentage_of_living_expenses,current_job_role_sat_rate,family_living_abroad,relatives_abroad,friends_it_migrated,plan_to_migrate,primary_reasons_for_migrating,timeframe_planning_to_migrate,preferred_country
0,32,Male,Unmarried,No,0,Government (State),Computer Science,3.27,Entrepreneur,Beep technologies pvt ltd,...,"Below 200,000",40% - 60%,1,No,0,20,Undecided,Not applicable,Not applicable,Not applicable
1,28,Male,Unmarried,No,4,Government (State),Electronics and Information technology,3.40,QA Engineer / UI/UX Designer,MillenniumIT,...,"200,000 - 500,000",40% - 60%,3,No,3,10,Undecided,Not applicable,Not applicable,Not applicable
2,24,Male,Unmarried,No,2,Private,Computer Science,3.00,Software Engineer / Developer,LOLC Technologies,...,"Below 200,000",My expenditures exceed my income,2,No,0,5,Yes,Higher Salaries and Better Financial Prospects...,Needs review,Schengen Countries
3,30,Female,Married,No,4,Government (State),Computer Science and Industrial Management,3.24,Project Manager,Infor Sri Lanka,...,"200,000 - 500,000",40% - 60%,5,No,10,8,Undecided,Not applicable,Not applicable,Not applicable
4,29,Male,Married,No,0,Private,Software Engineering,3.69,Software Engineer / Developer,IFS,...,"200,000 - 500,000",61% - 80%,3,No,15,10,Undecided,Not applicable,Not applicable,Not applicable

In [ ]:
print("Missing values before cleaning:")

print(df.isnull().sum())

Missing values before cleaning:
age                              0
gender                           0
marital_status                   0
breadwinner                      0
num_of_dep                       0
uni_type                         0
academic_spl                     0
final_gpa                        1
job_role                         0
workplace                        0
experience                       0
num_certs                        0
monthly_salary                   0
percentage_of_living_expenses    0
current_job_role_sat_rate        0
family_living_abroad             0
relatives_abroad                 0
friends_it_migrated              0
plan_to_migrate                  0
primary_reasons_for_migrating    0
timeframe_planning_to_migrate    0
preferred_country                0
dtype: int64

In [ ]:
print("Number of duplicate rows:")
print(df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates removed")

Number of duplicate rows:
0
Duplicates removed

In [ ]:
df.columns = df.columns.str.strip().str.lower()
print(df.columns.tolist())

print("Column names cleaned")

print(df.dtypes)
numeric_columns = [
    "age",
    "num_of_dep",
    "final_gpa",
    "experience",
    "num_certs",
    "current_job_role_sat_rate",
    "relatives_abroad",
    "friends_it_migrated"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

print(df.dtypes)

['age', 'gender', 'marital_status', 'breadwinner', 'num_of_dep', 'uni_type', 'academic_spl', 'final_gpa', 'job_role', 'workplace', 'experience', 'num_certs', 'monthly_salary', 'percentage_of_living_expenses', 'current_job_role_sat_rate', 'family_living_abroad', 'relatives_abroad', 'friends_it_migrated', 'plan_to_migrate', 'primary_reasons_for_migrating', 'timeframe_planning_to_migrate', 'preferred_country']
Column names cleaned
age                                int64
gender                            object
marital_status                    object
breadwinner                       object
num_of_dep                         int64
uni_type                          object
academic_spl                      object
final_gpa                        float64
job_role                          object
workplace                         object
experience                       float64
num_certs                          int64
monthly_salary                    object
percentage_of_living_expenses     object
current_job_role_sat_rate          int64
family_living_abroad              object
relatives_abroad                   int64
friends_it_migrated                int64
plan_to_migrate                   object
primary_reasons_for_migrating     object
timeframe_planning_to_migrate     object
preferred_country                 object
dtype: object
age                                int64
gender                            object
marital_status                    object
breadwinner                       object
num_of_dep                         int64
uni_type                          object
academic_spl                      object
final_gpa                        float64
job_role                          object
workplace                         object
experience                       float64
num_certs                          int64
monthly_salary                    object
percentage_of_living_expenses     object
current_job_role_sat_rate          int64
family_living_abroad              object
relatives_abroad                   int64
friends_it_migrated                int64
plan_to_migrate                   object
primary_reasons_for_migrating     object
timeframe_planning_to_migrate     object
preferred_country                 object
dtype: object

In [ ]:
df.columns = df.columns.str.strip()

categorical_columns = [
    "gender",
    "marital_status",
    "breadwinner",
    "uni_type",
    "family_living_abroad",
    "plan_to_migrate"
]

for column in categorical_columns:
    print("\n", column)
    print(df[column].value_counts(dropna=False))

 gender
gender
Male                 61
Female               33
Prefer not to say     2
Name: count, dtype: int64

 marital_status
marital_status
Unmarried    52
Married      44
Name: count, dtype: int64

 breadwinner
breadwinner
No     71
Yes    25
Name: count, dtype: int64

 uni_type
uni_type
Government (State)    56
Private               40
Name: count, dtype: int64

 family_living_abroad
family_living_abroad
No     63
Yes    33
Name: count, dtype: int64

 plan_to_migrate
plan_to_migrate
Yes          45
Undecided    28
No           23
Name: count, dtype: int64

In [ ]:
df[
    [
        "age",
        "final_gpa",
        "experience",
        "num_certs",
        "current_job_role_sat_rate"
    ]
].describe()

df.loc[
    (df["age"] < 18) | (df["age"] > 70),
    "age"
] = np.nan

df.loc[
    (df["final_gpa"] <= 0) | (df["final_gpa"] > 4),
    "final_gpa"
] = np.nan

df.loc[
    (df["experience"] < 0) | (df["experience"] > 50),
    "experience"
] = np.nan

df.loc[
    (df["current_job_role_sat_rate"] < 1) |
    (df["current_job_role_sat_rate"] > 5),
    "current_job_role_sat_rate"
] = np.nan

df.head()

,age,gender,marital_status,breadwinner,num_of_dep,uni_type,academic_spl,final_gpa,job_role,workplace,...,monthly_salary,percentage_of_living_expenses,current_job_role_sat_rate,family_living_abroad,relatives_abroad,friends_it_migrated,plan_to_migrate,primary_reasons_for_migrating,timeframe_planning_to_migrate,preferred_country
0,32.0,Male,Unmarried,No,0,Government (State),Computer Science,3.27,Entrepreneur,Beep technologies pvt ltd,...,"Below 200,000",40% - 60%,1.0,No,0,20,Undecided,Not applicable,Not applicable,Not applicable
1,28.0,Male,Unmarried,No,4,Government (State),Electronics and Information technology,3.40,QA Engineer / UI/UX Designer,MillenniumIT,...,"200,000 - 500,000",40% - 60%,3.0,No,3,10,Undecided,Not applicable,Not applicable,Not applicable
2,24.0,Male,Unmarried,No,2,Private,Computer Science,3.00,Software Engineer / Developer,LOLC Technologies,...,"Below 200,000",My expenditures exceed my income,2.0,No,0,5,Yes,Higher Salaries and Better Financial Prospects...,Needs review,Schengen Countries
3,30.0,Female,Married,No,4,Government (State),Computer Science and Industrial Management,3.24,Project Manager,Infor Sri Lanka,...,"200,000 - 500,000",40% - 60%,5.0,No,10,8,Undecided,Not applicable,Not applicable,Not applicable
4,29.0,Male,Married,No,0,Private,Software Engineering,3.69,Software Engineer / Developer,IFS,...,"200,000 - 500,000",61% - 80%,3.0,No,15,10,Undecided,Not applicable,Not applicable,Not applicable

In [ ]:
df.head(10)
df.info()
print("Missing values after cleaning:")

print(
    df.isnull()
    .sum()
    .sort_values(ascending=False)
)
print("Remaining duplicate rows:")

print(df.duplicated().sum())

print("Final dataset shape:")

print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            96 non-null     float64
 1   gender                         96 non-null     object
 2   marital_status                 96 non-null     object
 3   breadwinner                    96 non-null     object
 4   num_of_dep                     96 non-null     int64
 5   uni_type                       96 non-null     object
 6   academic_spl                   96 non-null     object
 7   final_gpa                      95 non-null     float64
 8   job_role                       96 non-null     object
 9   workplace                      96 non-null     object
 10  experience                     96 non-null     float64
 11  num_certs                      96 non-null     int64
 12  monthly_salary                 96 non-null     object
 13  percentage_of_living_expenses  96 non-null     object
 14  current_job_role_sat_rate      96 non-null     float64
 15  family_living_abroad           96 non-null     object
 16  relatives_abroad               96 non-null     int64
 17  friends_it_migrated            96 non-null     int64
 18  plan_to_migrate                96 non-null     object
 19  primary_reasons_for_migrating  96 non-null     object
 20  timeframe_planning_to_migrate  96 non-null     object
 21  preferred_country              96 non-null     object
dtypes: float64(4), int64(4), object(14)
memory usage: 16.6+ KB
Missing values after cleaning:
final_gpa                        1
age                              0
marital_status                   0
breadwinner                      0
num_of_dep                       0
gender                           0
uni_type                         0
academic_spl                     0
job_role                         0
workplace                        0
experience                       0
num_certs                        0
monthly_salary                   0
percentage_of_living_expenses    0
current_job_role_sat_rate        0
family_living_abroad             0
relatives_abroad                 0
friends_it_migrated              0
plan_to_migrate                  0
primary_reasons_for_migrating    0
timeframe_planning_to_migrate    0
preferred_country                0
dtype: int64
Remaining duplicate rows:
0
Final dataset shape:
(96, 22)

In [ ]:
def clean_specialization(value):

    if pd.isna(value):
        return pd.NA

    value_original = str(value).strip().rstrip(".")

    value_clean = re.sub(
        r"\s+",
        " ",
        value_original
    ).casefold()

    specialization_mapping = {

        # Computer Science
        "computer science": "Computer Science",
        "cs": "Computer Science",
        "bsc in computer science": "Computer Science",
        "bachelors of computer science special":
            "Computer Science",

        # Computer Science & Engineering
        "computer science engineering":
            "Computer Science & Engineering",

        "computer science & engineering":
            "Computer Science & Engineering",

        "computer science and engineering":
            "Computer Science & Engineering",

        "computer science engineer":
            "Computer Science & Engineering",

        "cse":
            "Computer Science & Engineering",

        # Software Engineering
        "software engineering":
            "Software Engineering",

        "software engineer":
            "Software Engineering",

        "se bsc":
            "Software Engineering",

        "specialization in software engineering":
            "Software Engineering",

        # Information Technology
        "it":
            "Information Technology",

        "information technology":
            "Information Technology",

        "bsc(it)":
            "Information Technology",

        "it- bsc":
            "Information Technology",

        # Information Systems
        "information systems":
            "Information Systems",

        "computing and information systems":
            "Information Systems",

        # Electronics / Telecommunications
        "electronic and telecommunication engineering":
            "Electronics & Telecommunication Engineering",

        "electronics & telecommunication engineering":
            "Electronics & Telecommunication Engineering",

        # Network
        "network engineer":
            "Network Engineering",

        "network engineering":
            "Network Engineering",

        # Artificial Intelligence
        "ai":
            "Artificial Intelligence",

        "ai engineer":
            "Artificial Intelligence",

        # Correct obvious typo
        "stat and coputer sceience":
            "Statistics and Computer Science",

        # Other case corrections
        "mechanical engineering":
            "Mechanical Engineering",

        "material science and engineering":
            "Material Science and Engineering",

        "computational physics":
            "Computational Physics",

        "management":
            "Management",

        "marketing":
            "Marketing",

        "data analysis":
            "Data Analysis",

        "data engineering":
            "Data Engineering",

        "data science":
            "Data Science",

        "data science and analytics":
            "Data Science and Analytics",

        "cybersecurity":
            "Cybersecurity",

        "network & cyber security":
            "Network & Cyber Security"
    }

    return specialization_mapping.get(
        value_clean,
        value_original
    )


df["academic_spl"] = (
    df["academic_spl"]
    .apply(clean_specialization)
    .astype("string")
)

In [ ]:
output_file = "/content/final_cleaned_dataset.csv"

df.to_csv(
    output_file,
    index=False
)

print("Final cleaned dataset created successfully.")
print(output_file)

from google.colab import files

files.download(
    "/content/final_cleaned_dataset.csv"
)

Final cleaned dataset created successfully.
/content/final_cleaned_dataset.csv